const { Router } = require('express');
const c = require('./payments.controller');
const { requireAuth } = require('../../middleware/auth');
const { requirePermission } = require('../../middleware/rbac');
const { validate } = require('../../middleware/validate');
const { idParamSchema, createSchema, reverseSchema } = require('./payments.schema');
const r = Router();
r.get('/', requireAuth, requirePermission('payment.view'), c.list);
r.post('/', requireAuth, requirePermission('payment.record'), validate({ body: createSchema }), c.create);
r.post('/stripe/webhook', c.stripeWebhook);
r.post('/:id/reverse', requireAuth, requirePermission('payment.reverse'), validate({ params: idParamSchema, body: reverseSchema }), c.reverse);
module.exports = r;
