const { Router } = require('express');
const c = require('./invoices.controller');
const { requireAuth } = require('../../middleware/auth');
const { requirePermission } = require('../../middleware/rbac');
const r = Router();
r.use(requireAuth);
r.get('/', c.list);
r.get('/statements', c.statement);
r.get('/aging', requirePermission('ADMIN', 'FINANCE_MANAGER'), c.aging);
r.get('/:id', c.get);
r.get('/:id/pdf', c.pdf);
module.exports = r;
