const { Router } = require('express');
const c = require('./cms.controller');
const { requireAuth, optionalAuth } = require('../../middleware/auth');
const { requirePermission } = require('../../middleware/rbac');
const { validate } = require('../../middleware/validate');
const { makeUploader } = require('../../middleware/upload');
const { createSchema, updateSchema } = require('./cms.schema');
const r = Router();
const mediaUpload = makeUploader('cms');
r.get('/blocks', optionalAuth, c.list);
r.get('/blocks/:key', optionalAuth, c.get);
r.post('/blocks', requireAuth, requirePermission('cms.edit'), validate({ body: createSchema }), c.create);
r.patch('/blocks/:key', requireAuth, requirePermission('cms.edit'), validate({ body: updateSchema }), c.update);
r.delete('/blocks/:key', requireAuth, requirePermission('cms.edit'), c.remove);
r.patch('/blocks/:key/publish', requireAuth, requirePermission('cms.edit'), c.togglePublish);
r.get('/media', requireAuth, requirePermission('cms.edit'), c.listMedia);
r.post('/media', requireAuth, requirePermission('cms.edit'), mediaUpload.single('file'), c.createMedia);
r.delete('/media/:id', requireAuth, requirePermission('cms.edit'), c.removeMedia);
module.exports = r;
