# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: en-US
early_access: false

reviews:
  profile: assertive
  request_changes_workflow: true
  high_level_summary: true
  in_progress_fortune: false
  poem: false
  review_status: true
  auto_review:
    enabled: true
    drafts: true
    auto_incremental_review: true

chat:
  art: false
