const { Router } = require('express');
const ctrl = require('./buyers.controller');
const { requireAuth } = require('../../middleware/auth');
const { requirePermission } = require('../../middleware/rbac');
const { validate } = require('../../middleware/validate');
const { approveSchema, rejectSchema, suspendSchema, creditUpdateSchema, tierUpdateSchema } = require('./buyers.schema');
const router = Router();
router.use(requireAuth);
const canViewBuyer = requirePermission('order.view.all', 'user.manage', 'credit.view');
const canManageBuyer = requirePermission('user.manage');
router.get('/', canViewBuyer, ctrl.list);
router.get('/:id', canViewBuyer, ctrl.get);
router.post('/:id/approve', canManageBuyer, validate({ body: approveSchema }), ctrl.approve);
router.post('/:id/reject', canManageBuyer, validate({ body: rejectSchema }), ctrl.reject);
router.post('/:id/suspend', canManageBuyer, validate({ body: suspendSchema }), ctrl.suspend);
router.post('/:id/reactivate', canManageBuyer, ctrl.reactivate);
router.patch('/:id/credit', canManageBuyer, validate({ body: creditUpdateSchema }), ctrl.updateCredit);
router.patch('/:id/tier', canManageBuyer, validate({ body: tierUpdateSchema }), ctrl.updateTier);
router.get('/:id/orders', canViewBuyer, ctrl.getOrders);
router.get('/:id/invoices', canViewBuyer, ctrl.getInvoices);
router.get('/:id/payments', canViewBuyer, ctrl.getPayments);
router.get('/:id/rma', canViewBuyer, ctrl.getRMA);
module.exports = router;
