const { Router } = require('express');
const ctrl = require('./buyers.controller');
const { requireAuth } = require('../../middleware/auth');
const { requirePermission } = require('../../middleware/rbac');
const { validate } = require('../../middleware/validate');
const { approveSchema, rejectSchema, suspendSchema, creditUpdateSchema, tierUpdateSchema } = require('./buyers.schema');
const router = Router();
router.use(requireAuth, requirePermission('ADMIN', 'SALES_MANAGER', 'BUYER_MANAGER'));
router.get('/', ctrl.list);
router.get('/:id', ctrl.get);
router.post('/:id/approve', validate({ body: approveSchema }), ctrl.approve);
router.post('/:id/reject', validate({ body: rejectSchema }), ctrl.reject);
router.post('/:id/suspend', validate({ body: suspendSchema }), ctrl.suspend);
router.post('/:id/reactivate', ctrl.reactivate);
router.patch('/:id/credit', validate({ body: creditUpdateSchema }), ctrl.updateCredit);
router.patch('/:id/tier', validate({ body: tierUpdateSchema }), ctrl.updateTier);
router.get('/:id/orders', ctrl.getOrders);
router.get('/:id/invoices', ctrl.getInvoices);
router.get('/:id/payments', ctrl.getPayments);
router.get('/:id/rma', ctrl.getRMA);
module.exports = router;
