const { Router } = require('express');
const c = require('./reports.controller');
const { requireAuth } = require('../../middleware/auth');
const { requirePermission } = require('../../middleware/rbac');
const { reportLimiter } = require('../../middleware/rateLimit');
const r = Router();
r.use(requireAuth, requirePermission('report.view'), reportLimiter);
r.get('/', c.dashboard);
r.get('/export', c.dashboard);
r.get('/summary', c.summary);
r.get('/sales-trend', c.salesTrend);
r.get('/category-performance', c.categoryPerformance);
r.get('/top-products', c.topProducts);
r.get('/buyer-behaviour', c.buyerBehaviour);
r.get('/credit-risk', c.creditRisk);
r.get('/inventory-turnover', c.inventoryTurnover);
r.get('/supplier-contribution', c.supplierContribution);
r.get('/returns-analytics', c.returnsAnalytics);
module.exports = r;
