const { Router } = require('express');
const c = require('./rma.controller');
const { requireAuth, requireApprovedBuyer } = require('../../middleware/auth');
const { requirePermission } = require('../../middleware/rbac');
const { validate } = require('../../middleware/validate');
const { createSchema, rejectSchema, receiveSchema, resolveSchema } = require('./rma.schema');
const r = Router(); r.use(requireAuth);
r.post('/', requireApprovedBuyer, validate({ body: createSchema }), c.create);
r.get('/', c.list);
r.get('/:id', c.get);
r.patch('/:id/approve', requirePermission('rma.decide'), c.approve);
r.patch('/:id/reject', requirePermission('rma.decide'), validate({ body: rejectSchema }), c.reject);
r.patch('/:id/receive', requirePermission('stock.adjust'), validate({ body: receiveSchema }), c.receive);
r.patch('/:id/resolve', requirePermission('rma.decide'), validate({ body: resolveSchema }), c.resolve);
module.exports = r;
